allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  maplibre-gl: true
  unrs-resolver: true
  vue-demi: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - maplibre-gl
  - unrs-resolver
  - vue-demi
