name: Sync Files to Production

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sinkron file ke server production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Connect ke Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: "1.80.3"

      - name: Sinkron file via rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
            --exclude='.git/'
            --exclude='node_modules/'
            --exclude='.nuxt/'
            --exclude='.output/'
            --exclude='backend/node_modules/'
            --exclude='backend/dist/'
            --exclude='logs/'
            --exclude='.env'
            --exclude='backend/.env'
          path: ./
          remote_path: /home/rifky/Public/aplikasi-karyawan-kokarsi/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
